### ISSUE TITLE
Animaciones de Sarah

### ISSUE THREAD

**Issue by elGuille** [elGuille/fallingsara#1]
Tienes que acordar un tamaño y pasarle a @carlozzer unos cuantos PNGs
Hemos acordado que se le moverán:
- brazos
- pelo

**Comment by anagalvan** [comment]
ok

**Comment by anagalvan** [comment]
Esta vez lo voy a dibujar y animar todo en flash, por lo que será más fácil cambiar los tamaños

**Comment by anagalvan** [comment]
Ahí va el primer pantallazo. Decidme qué os parecen los tamaños

https://www.dropbox.com/s/h9n6awekn26ubne/PantallazoSarah1.jpg

**Comment by elGuille** [comment]
Lo he visto cuando he visto el update en Dropbox. Me gusta mucho. Sabes que yo prefiero las cosas pequeñitas...

**Comment by anagalvan** [comment]
Ya tengo la animación de Sara cayendo, y los fondos también. Si os parece bien le paso @carlozzer los pngs

https://www.dropbox.com/s/lqlhmiasu46f961/SaraCayendo.swf

Las siguientes animaciones serían:
- animar a Sara cuando se mueva hacia la derecha e izquierda
- animar a Sara cuando roce algo malo (gesto de miedo)
- animar a Sara  cuando toque algo bueno (gesto de alegría)

**Comment by anagalvan** [comment]
Echadle un vistazo de nuevo, que me he equivocado de archivo. 

https://www.dropbox.com/s/lqlhmiasu46f961/SaraCayendo.swf

Ah, y si no podéis ver el swf, decídmelo y pongo un vídeo...

**Comment by carlozzer** [comment]
Puedo ver a Sara en movimiento en el flash.
A mí me vendrían guay los png
gracias!

2012/12/11 anagalvan notifications@github.com

**Comment by anagalvan** [comment]
ok, los preparo y te los paso

**Comment by anagalvan** [comment]
@carlozzer te paso los pngs

Aquí un ejemplo de formato a la resolución final:
https://www.dropbox.com/s/ktx7d49jf7husjq/Ejemploformato.jpg

Los pngs del fondo:
https://www.dropbox.com/sh/3aaj5xf10cfpl6t/BVPeEMphEo

La animación de Sara cayendo en pngs:
https://www.dropbox.com/sh/oupcfnvs3e57uso/49Q7dS-l1V

Dime si todo está ok

**Comment by carlozzer** [comment]
En principio todo OK
Esta tarde en casa lo meto en el proyecto y os cuento.

Solo una pregunta. He visto que del túnel solo hay una pared.
Qué hago la repito al otro lado invertido por ejemplo?

**Comment by anagalvan** [comment]
Yo la he puesto repetida, pero a destiempo, aunque puedo hacer otra nueva. Usa esa de momento, hasta que te pase otra.

Ah, la animación va a 24 pfs

**Comment by carlozzer** [comment]
ok, gracias.
Luego os cuento.

**Comment by elGuille** [comment]
Muy bien gente, sigamos así.

Merino, no te olvides de actualizar el repositorio en Dropbox para que podamos ver los cambios de manera automática en Unity.

Por si no lo hacias…

**Comment by anagalvan** [comment]
Ya tengo los movimientos de Sara a izquierda y derecha. Lo he planteado como un movimiento corto, después la figura vuelve a su posición original

El ejemplo:
https://www.dropbox.com/s/io7a921q1vcg0vq/SaraLateral.swf

Los pngs:

Derecha
https://www.dropbox.com/sh/s7hq485nfgon6oh/5v7C6lAogT

Izquierda:
https://www.dropbox.com/sh/vbakxqd6rhph4zb/51EOJQz8o8

**Comment by carlozzer** [comment]
No termino de conseguir lo del git, al final he terminado compiando los ficheros a la carpeta de dropbox.
Soy lo peor... :P

He puesto en el proyecto los nuevos gráficos excepto estos últimos de derecha e izquierda.
Me surgen varias dudas al ver el resultado.

¿Cómo escalar los planos para conseguir el mejor resultado con las texturas?
¿Cual es el mejor shader para las transparencias?

gracias!

**Comment by anagalvan** [comment]
No se por qué, pero los colores se ven apagados... y la niña como achatada... ¿se podría mantener la proporción? he pasado las imágenes al tamaño supuestamente real, no deberías necesitar escalar...pero si necesitas otra resolución o tamaño, dímelo.

la animación rara, o muy rápida o no se ven todos los frames...

**Comment by carlozzer** [comment]
Esta tarde vemos este tema si os parece.

**Comment by anagalvan** [comment]
ok, a las 20:30?

**Comment by carlozzer** [comment]
Por mí ok

**Comment by carlozzer** [comment]
Cuando llegue a casa probaré esto y os cuento.
http://forum.unity3d.com/threads/82265-Pixel-Perfect-and-Clean-Textures

**Comment by elGuille** [comment]
En principio sí!

**Comment by elGuille** [comment]
He probado lo del Unity remote y he jugado a Sara desde el móvil. Mola, aunque estaba en horizontal. Es muy fácil de usar, lanzas Unity en el pc, seleccionas la escena, le das al play y desde el móvil abres el Unity remote, introduces la ip de tu pc y voilá

**Comment by Johelious** [comment]
Mola!

**Comment by anagalvan** [comment]
Buenos días Carlos :) te quería comentar una cosa a ver si es posible:
- En los movimientos laterales de Sara, la animación se reproduce relativa al tiempo que tienes mantenido el botón y eso queda muy bien y muy suave, 
  pero me gustaría que se reprodujera toda la secuencia animada con un sólo toque, porque creo que la gente jugará así debido a la velocidad y no se aprecia la animación

Ya me dices si se puede y si queda bien...

**Comment by anagalvan** [comment]
Más cosas: 

Sigo viendo a Sara con alfa y las paredes no guardan su proporción, están achatadas

**Comment by anagalvan** [comment]
@carlozzer te paso los pngs de la animación de Sara cuando toca un objeto malo
- La animación va a 24 fps

https://www.dropbox.com/sh/2mcg0h5clfsm9k3/YIiTrLCw_I

**Comment by carlozzer** [comment]
Ayer conseguí que todo se vea mucho mejor, ya veréis. El miércoles incorporo las nuevas animaciones y lo subo todo a dropbox.
Hoy no voy a poder hacerlo.

La orientación hay que cambiarla para que se vea a Sara cayendo a lo largo del iphone/ipad, el caso es que en unity me sale Sara cayendo de izquierda a derecha. Se puede girar la preview en unity ??

**Comment by carlozzer** [comment]
Ah, y tb tengo pendiente lo de la animación lateral completa con un solo toque!!

**Comment by elGuille** [comment]
A ver si esto te ayuda:

http://answers.unity3d.com/questions/46542/created-a-vertical-game-for-iphone-android.html
