### ISSUE TITLE
Montar repositorio con Unity, Git y Dropbox

### ISSUE THREAD

**Issue by elGuille** [elGuille/fallingsara#2]
Si se te ocurre algo más sencillo pues adelante.

**Comment by elGuille** [comment]
Cómo va esto Meriniesh?

**Comment by carlozzer** [comment]
Me pongo con ello. Luego os cuento

**Comment by carlozzer** [comment]
He subido una primera version de unity de un cuadrado cayendo por un tunel.
Los planos existen en el editor de unity.
Voy a crear otra escena en que los planos se creen en tiempo real para conseguir un bucle infinito
Luego la subo cuando la tenga

Decidme si podéis verlo. Gracias!!

**Comment by elGuille** [comment]
Yo ya lo veo, muchas gracias nene.
De momento y hasta que lo veamos en pantalla mola. 
Solo se me ocurre decir que debería ser horizontal.  :P

**Comment by carlozzer** [comment]
Horizontal ??

de izquierda  a derecha ??

2012/12/8 Guille notifications@github.com

> Solo se me ocurre decir que debería ser horizontal. :P

**Comment by carlozzer** [comment]
Probad la escena 2

**Comment by elGuille** [comment]
Quería decir vertical.  :P  
La pruebo luego...

## 

Guille

**Comment by anagalvan** [comment]
Chavales, ahora me dejáis con la duda. ¿La pantalla estará en vertical o en horizontal como lo muestra Carlos?

**Comment by elGuille** [comment]
Vertical.

**Comment by carlozzer** [comment]
Es en Vertical, tengo que cambiar la resolución.

**Comment by anagalvan** [comment]
Vale, pues vuelvo a recordar el formato, 2048 x 1536 píxeles. La resolución 264 ppp. 

Estoy montando un pantallazo

**Comment by elGuille** [comment]
Se sale...

  https://github.com/notifications/beacon/B572Q6ButZGhPtbjDQ8WJ6V8_SVE6nPzb-IAxX2BD6YPngBJhFQbkwbFu7a0uYNs.gif
