### ISSUE TITLE
Lista de features a editar y aumentar

### ISSUE THREAD

**Issue by elGuille** [elGuille/fallingsara#3]
Las iremos repartiendo en tareas:
1.  Sin minimapa
2.  Barra de miedo, calaverita mexicana llenándose
3.  Cierto tiempo haciéndolo bien te pone boca abajo y te acelera haciéndote inmune durante hasta que lo hagas mal otra vez
4.  Objetos buenos un tipo de sonido
5.  Objetos malos otro
6.  Aura tipo dragonball al caer

**Comment by elGuille** [comment]
Ana, debería pasarle a Carlos cuando puedas alguna de las features, ya sea la calaverita, algún objeto aunque no sea final y algún otro diseño de Sara, puede ser en vertical con el aura o lo que te parezca.

**Comment by anagalvan** [comment]
Tres cosas:

-La barra de miedo
- El botón de pausa
- La animación de Sara cuando toca un objeto malo

Aquí el ejemplo. En breve los pngs
https://www.dropbox.com/sh/m43zs7vczy32w6b/CLOKXAbhwN

**Comment by anagalvan** [comment]
@carlozzer te paso los pngs de la Barra de Miedo. Te cuento:

Hay 11 imágenes, del 0% (de miedo) hasta el 100% respectivamente. No se deben escalar, van a su proporción.

https://www.dropbox.com/sh/uo7ynqo7e2zy3pu/c2KLe8Ulsg

**Comment by anagalvan** [comment]
@carlozzer te paso los pngs el botón de Pausa y el de Play 

-con su imagen en el estado "Over" cada uno

https://www.dropbox.com/sh/uw05wfipmny1xt3/SiDxI4bjMJ

**Comment by carlozzer** [comment]
Gracias Ana, esta tarde me pongo con ello.
