### ISSUE TITLE
Primeros objetos

### ISSUE THREAD

**Issue by elGuille** [elGuille/fallingsara#4]
Ana tiene que entregar los primeros objetos a programación.
He añadido una hoja de excel compartida donde podemos ir escribiendo objetos buenos y malos.
Hay una lista por cada uno de nosotros, molaría ir viendo como la acuatizáis.

**Comment by anagalvan** [comment]
@Johelious @elGuille @carlozzer 

Hola, cómo estáis? Veo esto un poco parado, no? 

Yo, a ratos, voy a ir poniendo objetos en dropbox. Aquí tenéis unos cuantos objetos buenos:

https://www.dropbox.com/sh/teba6jkmn6l7knm/qpHO1k1uoo

**Comment by Johelious** [comment]
Wenas! Necesitamos a Merino de vuelta! Merino! Como va tu internet?

**Comment by carlozzer** [comment]
Yo ya tengo Internet en casa otra vez, ya puedo retomarlo :)
Esta tarde me pongo con las cosas pendientes y estas imágenes de objetos
(muy chulas por cierto)

2013/1/14 anagalvan notifications@github.com

**Comment by carlozzer** [comment]
jeje, bien gracias, ya tengo internet!!!
esta tarde le doy cañita ;)

2013/1/15 Johelious notifications@github.com

> Wenas! Necesitamos a Merino de vuelta! Merino! Como va tu internet?
>
