### ISSUE TITLE
Barra de miedo

### ISSUE THREAD

**Issue by anagalvan** [elGuille/fallingsara#6]
Hola, he hecho los cambios en la barra de miedo. 

Aquí está la barra por un lado con 30 estados:
https://www.dropbox.com/sh/bacxubr49wr6o4r/gzMjmuFFqs

Y la carita por otro:
https://www.dropbox.com/sh/m2iqmgvkwi5vw6s/sg1vydsEdA

Decidme si está Ok. No os cortéis en decirme las cosas, que yo os las diré a vosotros también ;))

**Comment by elGuille** [comment]
Es decir que hay que cojer 3 objetos para cambiar de cara. No debería haber solo 10 caras? La primera y la segunda son iguales, no?

**Comment by anagalvan** [comment]
Cierto, se me ha repetido la primera cara. Ya está arreglado:

https://www.dropbox.com/sh/m2iqmgvkwi5vw6s/sg1vydsEdA

**Comment by elGuille** [comment]
En cuanto esté implementada cerramos esta
