### ISSUE TITLE
Visualización gráficos

### ISSUE THREAD

**Issue by anagalvan** [elGuille/fallingsara#7]
Hola a todos, ya sé que andáis liados con cuestiones técnicas de Unity, pero hay algo que me preocupa en cuanto a los gráficos.

Es muy importante que las imágenes se vean nítidas y con mucha calidad, y no lo estamos consiguiendo. Creo que hay que arreglar esto antes de seguir programando. 

He hecho un pantallazo con las  imágenes que yo genero y las que veo en Unity (a la máxima calidad) . No pido que sean exactamente iguales, pero hay bastante diferencia:
https://www.dropbox.com/s/ptmulls7ef84w7z/VisualizaconGraficos.jpg

Yo estoy trabajando con el formato Ipad 3 (2048 x 1536 píxeles) con 264 ppp de resolución. Los gráficos están a su tamaño real, no hay que escalarlos ni ponerles fades, deberían verse nítidos.

**Comment by elGuille** [comment]
Si @Johelious sabe porqué pasa esto que lo diga ahora o calle para siempre.

**Comment by carlozzer** [comment]
Hola Ana, en un par de días retomo el tema y os enseño resultados.
Lo próximo que veáis será más nítido y con más calidad. seguro!! :)

2013/1/8 anagalvan notifications@github.com

**Comment by elGuille** [comment]
Gracias Merino. Si necesitas ayuda o no sabes por qué pasa esto pregúntanos y  nos ponemos a investigar.

**Comment by anagalvan** [comment]
Gracias Carlos. Y si necesitas que te vuelva a pasar alguna imagen, dímelo

**Comment by carlozzer** [comment]
No he podido terminar todo lo que quería hacer, pero al menos creo que ahora se ve más nítido.
He subido una nueva versión a dropbox. Por favor, probadlo cuando podáis y me decís si así vale
o si hay que seguir mejorando los gráficos.

**Comment by anagalvan** [comment]
Hola Carlos, ahora se ve mucho mejor :) quizá le falta un poco de suavizado al personaje, que se pixela un poco.

Las paredes, aunque se ven muy nítidas, siguen sin guardar la proporción en el eje Y, o sea, achatadas hacia abajo. Las hice más largas de la altura de la pantalla para que pudieran moverse a modo de máscara y no diera la sensación de que se repiten. Pero si quieres te las paso de otra forma, en trozos más pequeños o algo así...

**Comment by carlozzer** [comment]
tal como está ahora los planos de las paredes son mucho más altos que el
tamaño de la cámara,
no obstante gracias por la info, miraré la proporción vertical.

2013/1/16 anagalvan notifications@github.com

**Comment by anagalvan** [comment]
Guay. Gracias Carlos
