### ISSUE TITLE
Sistema de control de aparición de objetos

### ISSUE THREAD

**Issue by Johelious** [elGuille/fallingsara#8]
Este sistema intenta darme las herramientas necesarias para controlar la aparición de los objetos del juego, su velocidad y sus valores básicos de forma que el juego se pueda editar fácilmente,

Lo ideal para mi es que todos los objetos esten controlados desde el mismo script y poder cambiarles las siguientes variables a cada uno independientemente.
- Valor de miedo: la cantidad que agrega o quita de miedo (puede ser negativo)
- indice de aparicion: el porcentaje de que aparezca ese objeto.
- multiplicador de la velocidad: algo como, 0.8, este objeto multiplicara la velocidad a la que van los objetos x 0.8 (luego lo explico)

Tambien necesitaré poder controlar la progresion de los objetos que aparecen, es deir, como van entrando por abajo de la pantalla. Para ello deberia poder controlar estas otras variables desde otro script.
- Tiempo entre objetos: el tiempo que pasa desde que sale el primer objeto hasta el siguiente.
- Tiempo entre objetos 2: un tiempo entre objetos distinto.
- Tiempo entre objetos 3: otro distinto.
- Asi hasta 10 distintos.

Los objetos aparecen en una posicion X aleatoria del fondo del agujero. Y se mueven hacia arriba a una velocidad determinada. La velocidad de los objetos irá subiendo en funcion de los siguientes valores:
- Tiempo 1: la cantidad de tiempo en el cual los objetos se mueven a la velocidad 1.
- Tiempo 2: la cantidad de tiempo en el cual los objetos se mueven a la velocidad 2.
- Asi hasta 10.
- Velocidad 1: una velocidad a la cual suben los objetos.
- Velocidad 2: una velocidad distinta a la que suben esos objetos.
- Asi hasta 10.

Lo mejor seria que yo mismo pudiese crear la cantidad de velocidades y tiempos que quisiera 10 o las que sean).

Creo que lo ideal sería que chateásemos un día y te o explico bien. Yo me he cambiado la conexión a fibra 100Mb así que el skype debería ir como un tiro...
¡Cuando os iría bien?

**Comment by carlozzer** [comment]
He implementado el sistema para los objetos

Dentro de la jerarquía, en el GameObject "ItemFactory" hay dos propiedades públicas que se pueden modificar desde el editor:

Nota: los rangos se componen de dos enteros, el mínimo y el máximo, el engine calcula un número aleatorio entre ambos. Si queremos que sea siempre el mismo número, ponemos el mínimo y el máximo iguales.

Objetos
   |--- Size (no tocar)
   |--- Cerdito
   |         |---- Resource (no tocar)
   |         |---- Miedo(núm entero [0..30], es el daño que hace a Sara, negativo quita miedo, positivo aumenta miedo)
   |         |---- Prioridad (sirve para regular la prioridad de aparición de dicho item, lo explico más abajo (*))
   |         |---- Amplitude (rango) cantidad de "serpenteo" movimiento horizontal del objeto
   |         |---- Rotation (rango) velocidad rotación, negativo y positivo para cambiar el sentido de la rotación.
   |         |          Si es cero no rota
   |         |---- Speed (rango) velocidad del objeto
   |
   |---  Caramelo (siguiente objeto)
  ...
  ...

Al final he puesto todas las propiedades del objeto en el mismo sitio, así no hay que buscar otras propiedades en otros lugares del editor, si no mola lo hablamos.

Fases
   |--- Size (no modificar)
   |--- Element0
   |       |--- Frecuencia (float) tiempo que tarda en generar un objeto (en segundos)
   |       |--- Duración (float) tiempo que dura la fase (en segundos)
   |       |--- Multiplicador (float) multiplicador que se aplica a la velocidad de los objetos
   |
   |--- Element1  (siguiente fase, desde la 0 hasta la 9)
  ...
  ...

Cuando llega a la última fase se queda siempre en esa fase

(*) Prioridad
He implementado el siguiente sistema
se crea una lista en la que aparecen todos los objetos, y cada objeto aparece en esa lista el número de veces establecido por su prioridad. 
Después se selecciona un elemento de forma aleatoria en dicha lista, teniendo más posibilidades los objetos con mayor prioridad

un ejemplo simplificado:
si tenemos 3 objetos

obj1  prioridad 5
obj2  prioridad 2
obj3  prioridad 1

crea en memoria esta lista:

obj1
obj1
obj1
obj1
obj1
obj2
obj2
obj3

y de esta lista selecciona un elemento aleatoriamente, teniendo en este caso, más posibilidades de ser seleccionado el obj1

Cualquier duda o lo que sea, lo vamos comentando.

Saludos!! :)

**Comment by carlozzer** [comment]
Acabo de subir la última versión.

**Comment by elGuille** [comment]
Me pongo a verla ya. Gracias. :)
